Model/Repository Member OT278-23
alkemyTech/OT278-server pull request #1
Opened 2022-08-18 13:39 UTC by LucasLopezd

SUMARY:

- Model Member added
- Repository Member added

2022-08-19 03:06 UTC, turcoamado requested changes
Te deje dos comentarios. Con respecto a los nombres de las columnas en la DB yo quizas evitaria escribir el member por delante, pero no esta mal por eso no te puse que lo modifiques. Si seria bueno que opten por una sola forma como para intentar mantener un estandar tambien alli

2022-08-19 03:06 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Member.java
> +@SQLDelete(sql = "UPDATE members SET member_deleted = TRUE WHERE member_id = ?")
Esto esta bien pero incompleto, te esta faltando definir la clausula where con la annotation @Where justamente

2022-08-19 03:06 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Member.java
> +    @Column(name = "member_name", length = 35, nullable = false)
Para este campo que no puede ser nulleable le falta agregar un mensaje de error en caso de que nos este faltando el atributo en el request. Lo mismo para la imagen, para el caso de las fechas no seria necesario ya que se setean automaticamente

2022-08-19 13:07 UTC, LucasLopezd commented
Turko, hice algunas modificaciones en la entidad según tus correcciones, espero tu respuesta.

2022-08-20 22:20 UTC, turcoamado approved these changes
buenisimo!

2022-08-21 21:36 UTC, merged