create model&repository
alkemyTech/OT278-server pull request #12
Opened 2022-08-24 01:47 UTC by Damian-Pereyra-dv

2022-08-24 13:50 UTC, turcoamado requested changes
te deje algunos comentarios

2022-08-24 13:50 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Category.java
> +    @NotNull
Estaria bueno agregarle un mensaje de error para cuando en el request no se envie el parametro muestre el mensaje de error. Esto se puede hacer dentro de la misma annotation que ya utilizaste y quedaria algo como: `@NotNull(message = "Name cannot be empty")`

2022-08-24 13:50 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Category.java
> +    private LocalDateTime creationDate = LocalDateTime.now();
A esta variable le podrias poner la annotation @CreationTimestamp. Y de paso crear un campo para la fecha de actualizacion, que se puede anotar con la annotation @UpdateTimestamp

2022-08-24 14:12 UTC, turcoamado commented
Ojo que estabas haciendo el PR a main, te lo cambie a develop!

2022-08-25 21:21 UTC, Damian-Pereyra-dv reviewed
feature/OT278-19 arreglo

2022-08-25 22:24 UTC, turcoamado approved these changes
buenisimo! ahora si

2022-08-26 00:04 UTC, Damian-Pereyra-dv commented
perdon Yamil! pero no me deja mergear a Develop, porque me indica que esta aprovado para mergear en el Main, tendre q hacer una nueva pullRequest?

2022-08-26 20:24 UTC, turcoamado commented
Damian como estas? No te deja mergear porque tenes un conflicto que resolver (en el pom). Yo le cambie el destino al PR, y si te sucede de nuevo no hace falta generar un PR nuevo, se puede editar cambiando hacia donde se quiere mergear

2022-08-27 00:46 UTC, merged