New category ot278 43
alkemyTech/OT278-server pull request #26
Opened 2022-08-29 19:12 UTC by LucasLopezd

Request:
![new-category-request](https://user-images.githubusercontent.com/96482300/187279293-4fb3fbd3-35e7-404b-9061-5053de4fd3f9.png)

Response:
![new-category-response](https://user-images.githubusercontent.com/96482300/187279309-036a9df3-01e9-48a6-9bcc-49681e25056d.png)

2022-08-29 20:32 UTC, LucasLopezd commented
no estoy seguro de que sea la forma correcta de envíar un json al endpoint, me prodrías sugirir otra alternativa?

-enviar por separado los datos tampoco me pareció correcto

2022-08-30 12:18 UTC, turcoamado requested changes
Te puse algunas observaciones. Lo que dejaste como TODO en el service esta bien, hay que tenerlo en cuenta un poco mas adelante para que no quede sin hacer

2022-08-30 12:18 UTC, turcoamado commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +        entity.setCreationTimestamp(Timestamp.valueOf(LocalDateTime.now()));
aca no esta bien setearle el tiempo, porque el mapper podria utilizarse para cualquier otra cosa tambien, para algun tratamiento de datos interno. Lo que hay que hacer es setear esos valores en el servicio. Un ejemplo, suponete que estamos actualizando la categoria, deberiamos hacer uso de este mapper tambien, pero se se le esta seteando la fecha de creacion, por lo que pisaria la real por la que toma aca.
Deberia ser como los otros campos, `dto.getCreationTimestamp()` y `dto.getUpdateTimeStamp()`

2022-08-30 12:18 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +            TODO: <- ImageService should validate and return the path of the File...
Bien! Cuando este el servicio de amazon implementado hay que finalizar esto

2022-08-30 12:18 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        Category categorySaved = categoryRepository.save(category);
faltaria realizar al menos una validacion para saber si la categoria ya existe, habria que ir a buscar a la DB si tenemos una categoria con el nombre que se esta ingresando guardar, si es asi entonces deberiamos arrojar una exception indicando que ya existe. Se puede hacer dentro de un bloque try catch o lanzando la exception con la palabra throw

2022-08-30 12:18 UTC, turcoamado commented on pom.xml
> -		<dependency>
Esta bien que se elimine esta validacion? Me parece que esta por los mensajes en las entities

2022-08-30 12:18 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    @RolesAllowed(value = "ADMIN")
No esta mal, pero es preferible poner los permisos de los endpoints en el archivo de configuracion de spring security mediante los `.antMatchers()`

2022-08-30 12:18 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    @RolesAllowed(value = "ADMIN")
No esta mal, pero es preferible poner los permisos de los endpoints en el archivo de configuracion de spring security mediante los `.antMatchers()`

2022-08-30 12:18 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    public ResponseEntity<CategoryResponseDto> create(@Valid @RequestParam String dto,
Con respecto a tu consulta sobre enviar los datos al endpoint, podrias haber hecho lo siguiente:

```
@PostMapping //aca ya definis que es un POST 
public ResponseEntity< CategoryResponseDto > addNewCategory(@Valid @RequestBody CategoryRequestDto categoryDto) {
```

La imagen deberia ir en el DTO del request, no como archivo separado. Eso quizas era lo que no te supe entender en la daily de ayer

2022-08-30 12:32 UTC, LucasLopezd commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +        entity.setCreationTimestamp(Timestamp.valueOf(LocalDateTime.now()));
entiendo.

2022-08-30 12:34 UTC, LucasLopezd commented on pom.xml
> -		<dependency>
la he quitado porque no compila el código y tiraba muchos warnings de vulneravilidad, voy a revisar.

2022-08-30 12:38 UTC, LucasLopezd commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    public ResponseEntity<CategoryResponseDto> create(@Valid @RequestParam String dto,
si, entiendo, yo creo que la forma en que envío el dto no es correcta, es un String largo. Por ende no se esta validando con @Valid en el controlador. podría usar el método que usó federico usando la anotación @ModelAtribute?

2022-08-31 04:23 UTC, turcoamado requested changes
Muy bueno el tema de los mensajes y las excepciones!! Acordate de como definir el permiso para el endpoint (lo de usuario ADMIN) y la validacion en el servicio de que si ya existe una categoria con ese nombre.
Con respecto a la imagen en el endpoint fijate lo que te mencione, es mas sencillo de lo que estas planteando

2022-08-31 04:23 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    @RolesAllowed("ADMIN")
Acordate lo que te mencione de definir el rol, es preferible hacerlo en el archivo de configuracion de jwt

2022-08-31 04:23 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +                                                        @RequestPart(required = false) MultipartFile image){
Te la estas complicando, la imagen deberia ir en el dto. Es decir, categoryRequestDto tiene que tener un campo que sea para la imagen, el mismo sera un String, analogo con como se definio en la entity.
Para cargar esa imagen hay que obtener el string correspondiente a la imagen decodeada en base64, si queres por ahora no tengas en cuenta para la subida y ponele cualquier cosa como una rura, para chequear que el endpoint funciona, luego le prestamos atencion al tema de subioda de imagenes

2022-08-31 04:28 UTC, turcoamado reviewed
ya vi el tema del mensaje de si la categoria ya existe, disculpa

2022-09-01 04:25 UTC, turcoamado approved these changes
ahora si! barbaro!

2022-09-01 04:25 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/SecurityConfiguration.java
> +                .antMatchers("/categories/new").hasRole("ADMIN")
Claro! Esto te decia, perfecto!

2022-09-01 04:25 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        categories.forEach(c -> {
No se si te lo habia mencionado, pero muy bueno el uso de esta expresion lambda

2022-09-01 10:46 UTC, merged