Testimonials model/repository ot278 21
alkemyTech/OT278-server pull request #3
Opened 2022-08-19 15:14 UTC by FedericoCarrasco

SUMMARY:

- Add Testimonial entity.
- Add Testimonial repository.

2022-08-21 17:15 UTC, turcoamado requested changes
Te deje unos comentarios. Perdon la demora en la revision

2022-08-21 17:15 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Testimonial.java
> +    private LocalDateTime creationDate = LocalDateTime.now();
aca podrias hacer uso de la annotation `@CreationTimestamp` y dejarlo como
```
@Column(name = "creation_date",updatable = false)
private LocalDate creationDate;
```
y faltaria agregar un campo para la fecha de actualizacion, que quedaria similar pero con la annotation `@UpdateTimestamp`

2022-08-21 17:17 UTC, turcoamado requested changes
Justo actualizaste el PR! Joya, bueno fijate unicamente lo de las annotations de Lombok para ver si puede quedar sin el constructor

2022-08-21 17:17 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Testimonial.java
> +    public Testimonial (String name, String image, String content) {
Los constructores deberian poder ser reemplazado con la annotation de Lombok ```
@NoArgsConstructor
@AllArgsConstructor
```

2022-08-21 17:20 UTC, FedericoCarrasco commented on src/main/java/com/alkemy/ong/model/Testimonial.java
> +    public Testimonial (String name, String image, String content) {
El @AllArgsConstructor no me pisaría las propiedades que se inician automáticamente como creationDate y deleted?

2022-08-21 18:00 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Testimonial.java
> +    public Testimonial (String name, String image, String content) {
Yo creo que no, sinceramente no lo recuerdo pero lo hemos utilizado en otros grupos y nadie tuvo drama. Quizas le setea como parametro lo que se esta definiendo en el setter. Aca te dejo un link que encontre recien con algunas explicaciones de Lombok, esta en espaniol (perdon no tengo enie) https://www.paradigmadigital.com/dev/proyecto-lombok-facilitame-la-vida/

2022-08-21 18:16 UTC, FedericoCarrasco commented on src/main/java/com/alkemy/ong/model/Testimonial.java
> +    public Testimonial (String name, String image, String content) {
Ahí actualicé el PR con los cambios.

2022-08-22 20:01 UTC, turcoamado approved these changes
joyaa

2022-08-22 20:24 UTC, merged