add endpoint Organization/mapper & service
alkemyTech/OT278-server pull request #34
Opened 2022-09-01 03:51 UTC by Damian-Pereyra-dv

2022-09-01 04:43 UTC, turcoamado requested changes

2022-09-01 04:43 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +        Organization orgPublicInfo = organizationRepository.findAll();
aca tenes un problema, el `findAll()` te va a traer una lista, y vos estas esperando un objeto, por ende esto seguramente ni te este compilando. La forma correcta, mas alla de que asumamos que tenemos una unica organizacion, seria de ese listado traer el primer elemento que encuentro: `Organization orgPublicInfo = organizationRepository.findAll().stream().findFirst()`. Luego deberiamos chequear que efectivamente tengo algo, porque si esta null tenemos que mostrar un mensaje de error, entonces antes del return final por ejemplo podria quedar algo asi:
```
if (orgPublicInfo.isEmpty()) {
            throw new NotFoundException(messageSource.getMessage("organization.not.found", null, Locale.ENGLISH));
        }
```
agregando el mensaje al message.properties

2022-09-01 21:48 UTC, Damian-Pereyra-dv commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +        Organization orgPublicInfo = organizationRepository.findAll();
gracias turco! ahi pushee la corrección, avisame porfa

2022-09-02 05:16 UTC, turcoamado approved these changes
buenisimo

2022-09-02 15:58 UTC, merged