Ot278 41
alkemyTech/OT278-server pull request #39
Opened 2022-09-02 23:46 UTC by FedericoCarrasco

Summary:

- Add Get categories endpoint.

Pregunta: Debería devolver un solo DTO con una propiedad de tipo lista que contenga los nombres o es correcto que devuelva una lista de DTOs que contengan la propiedad nombre?

<img width="852" alt="Screen Shot 2022-09-02 at 20 38 13" src="https://user-images.githubusercontent.com/75759984/188246940-cb90d8e6-7bf5-4a08-a66e-f353f27666cd.png">

2022-09-03 01:16 UTC, turcoamado requested changes
Con respecto a tu pregunta, esta bien como lo planteaste, hay que devolver una lista de ese dto

2022-09-03 01:16 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    private final ICategoryService service;
Bien este cambio!

2022-09-03 01:16 UTC, turcoamado commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +        for (Category entity : entities) {
No esta mal, pero esto tambien lo podrias haber resuelto mediante una expresion lambda:
`entities.forEach { category ->
       CategoryNameDto dto = new CategoryNameDto();
       dto.setName(category.getName());
       dtoList.add(dto);
}`

incluso se podria performar aun mas explotando un poquito la programacion funcional, pero asi al aire no se me ocurre ahora

2022-09-03 01:16 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        List<Category> entities = repository.findAll();
Lo que haria aca seria devolver un mensaje en caso de que la lista este vacia, con alguna exception. Para en lugar de mostrar un json vacio que se visualice un mensaje indicando que no hay categorias cargadas o algo asi.

2022-09-03 04:58 UTC, FedericoCarrasco commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +        for (Category entity : entities) {
Estuve leyendo sobre programación funcional en Java y terminé implementando un map, creando por fuera un método para pasar de Category a CategoryNameDto. 
Cuando intenté con .forEach() no encontré forma de pasar de Array<Entity> a Array<DTO> sin tener errores, incluso usando el método extra.
Hay forma más limpia de hacerlo?

2022-09-03 05:07 UTC, FedericoCarrasco commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        List<Category> entities = repository.findAll();
Pude probar la forma de usar excepciones que implementó Lucas. 
No se me había ocurrido tirar una excepción ahí, gracias.

2022-09-03 12:29 UTC, LucasLopezd commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +        for (Category entity : entities) {
podrias usar algo así:

public <S, D> List<D> mapAll(List<S> sourceList, Class<D> destinationClass) {
        return sourceList.stream()
                .map(e -> map(e, destinationClass))
                .collect(toList());
    }

2022-09-03 14:28 UTC, FedericoCarrasco commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +        for (Category entity : entities) {
Sí Lucas, justo en la corrección del PR lo dejé así:

    public List<CategoryNameDto> CategoryEntityList2CategoryNameDtoList(List<Category> entities) {
        return entities.stream()
                    .map(this::CategoryEntity2CategoryNameDto)
                    .collect(Collectors.toList());
    }

2022-09-05 03:46 UTC, turcoamado approved these changes
Buenisimo

2022-09-05 03:46 UTC, turcoamado commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +        return entities.stream()
quedo muy bien!

2022-09-05 16:56 UTC, merged