Feature 46
alkemyTech/OT278-server pull request #43
Opened 2022-09-04 21:53 UTC by GianBarritta

**SUMMARY**

Creation endpoint News with method GET

//Pregunta: ¿Como puedo solucionar esto? me tira este error y la unica solución que me da el IDE es que le agregue el 'trows NotFoundException' a todo

![Screenshot from 2022-09-04 18-23-17](https://user-images.githubusercontent.com/98044720/188334881-79dfe5d7-f813-4ba4-86cb-ce94cea86278.png)

2022-09-05 04:17 UTC, turcoamado requested changes

2022-09-05 04:17 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
> +    public News getNewsById(Long id) throws NotFoundException {
Asi como esta planteado este deberia ser un metodo privado, porque lo estas utilizando dentro del metodo anterior getById(), y no se utiliza mas en el resto del codigo. Entonces si lo haces privado te ahorras la firma en la interface

2022-09-05 15:30 UTC, GianBarritta commented on src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
> +    public News getNewsById(Long id) throws NotFoundException {
entiendo, no me habia percatado, ahi lo modifico :+1:

2022-09-06 03:26 UTC, turcoamado commented
Este PR quedaria deprecado, deberias crear uno con la rama que vimos mas temprano. **feature-46_bis**

2022-09-06 13:43 UTC, closed without merging