Implements Upload images
alkemyTech/OT278-server pull request #44
Opened 2022-09-05 12:33 UTC by OscarTalero

Reusable service to upload images

2022-09-06 04:09 UTC, turcoamado requested changes

2022-09-06 04:09 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/AmazonClientImpl.java
> +    public MultipartFile base64ToImage(String encoded, String fileName) {
Este metodo podria ser privado ya que unicamente se esta utilizando dentro de esta clase

2022-09-06 04:09 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/AmazonClientImpl.java
> +            File file = convertMultiPartToFile(multipartFile);
Fijate que las lineas 84 a 86 se utilizan tambien en el metodo **uploadFile()**, podrias meter todo en un metodo  y simplemente reemplazar las lineas que se repiten por el metodo creado.

Al margen del comentario que te hice, para que se utiliza este metodo? Porque es lo mismo que indica el metodo **uploadFile()**, por lo que podris modificar el que esta hecho por el que hiciste vos que tiene mejores excepciones y estas catcheando los errores

2022-09-06 04:09 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/AmazonClientImpl.java
> +            throw new UnableToSaveEntityException("s3 amazon not available for save File");
El mensaje de error podria ponerse en el properties de mensajes

2022-09-06 11:43 UTC, OscarTalero commented on src/main/java/com/alkemy/ong/service/impl/AmazonClientImpl.java
> +    public MultipartFile base64ToImage(String encoded, String fileName) {
Cambio realizado

2022-09-06 19:26 UTC, turcoamado requested changes

2022-09-06 19:26 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/IAmazonClient.java
> +    public Image uploadFile(MultipartFile multipartFile);
los public sacaselos, como es una interface se asumen siempre como publicos y seria redundante escribirlos

2022-09-06 19:26 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/AmazonClientImpl.java
> +    public Image uploadFile(MultipartFile multipartFile) {
antes de cambiar esto chequeaste para que se usaba el uploadFile? porque por alguna razon estaba devolviendo la ruta, ahora lo haces devolver un Image y esto va a fallar la implementacion que ya existia.
Quizas el error fue mio que no me di cunta del tipo de dato que se estaba retornando en un metodo o en otro, no lo veo mal a nivel codigo, pero chequeate eso que te comente porque sino se va a romper algo

2022-09-06 19:26 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/AmazonClientImpl.java
> +            System.out.println("IllegalStateException : " + e);
en lugar de System.out es mejor practica utilizar Logs

2022-09-06 23:48 UTC, OscarTalero commented on src/main/java/com/alkemy/ong/service/IAmazonClient.java
> +    public Image uploadFile(MultipartFile multipartFile);
Listo

2022-09-07 00:00 UTC, OscarTalero commented on src/main/java/com/alkemy/ong/service/impl/AmazonClientImpl.java
> +    public Image uploadFile(MultipartFile multipartFile) {
Revise, y el metodo uploadFile no se utiliza en otra parte, de cualquier manera la Clase Image tiene un atributo String que contiene el mismo resultado, con lo cual si es necesraio se podria traer.

2022-09-07 00:22 UTC, OscarTalero commented on src/main/java/com/alkemy/ong/service/impl/AmazonClientImpl.java
> +            System.out.println("IllegalStateException : " + e);
Resuelto con log4j

2022-09-08 01:38 UTC, turcoamado approved these changes
Buenisimo Oscar! Buen laburo!

2022-09-08 10:59 UTC, merged