Ot278 22/activity model
alkemyTech/OT278-server pull request #5
Opened 2022-08-19 21:09 UTC by vlambo3

Add model and repository off Activity

2022-08-20 23:12 UTC, turcoamado requested changes
Te deje algunas observaciones Vani. Disculpa la falta de tildes, tengo el layout en ingles

2022-08-20 23:12 UTC, turcoamado commented on src/main/java/com/alkemy/ong/repository/ActivityRepository.java
> +public interface ActivityRepository extends JpaRepository<Activity, Long> {
Te falto la annotation @Repository

2022-08-20 23:12 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Activity.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE)
Aca conviene utilizar como strategy IDENTITY, funciona de la misma manera que el SEQUENCE pero para MySql performa mejor

2022-08-20 23:12 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Activity.java
> +    @NotNull
Te faltaria agregar el mensaje de error en los casos que son NotNull en caso de que en el request no se ingrese el valor y el mismo esta siendo requerido. Se puede hacer dentro de la misma annotation y podria ser algo como:` @NotNull(message = "name can not be null")`

2022-08-20 23:12 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Activity.java
> +    LocalDateTime timestamps = LocalDateTime.now();
yo le pondria un nombre mas significativo, que indique que es la fecha de creacion, y podrias hacer uso de la annotation `@CreationTimestamp`, por ejemplo:
```
@Column(name = "creation_date")
private LocalDateTime creationDate;
```
Y agregaria un campo mas para la fecha de actualizacion, utilizando la annotation `@UpdateTimestamp`
```
@UpdateTimestamp
@Column(name = "update_date")
private LocalDateTime updateDate;
```

2022-08-22 18:37 UTC, vlambo3 commented on src/main/java/com/alkemy/ong/model/Activity.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE)
Siii, lo charlamos en la daily del viernes, pero no llegué a cambiarlo en el código, gracias!

2022-08-22 18:42 UTC, vlambo3 commented on src/main/java/com/alkemy/ong/model/Activity.java
> +    LocalDateTime timestamps = LocalDateTime.now();
acá me queda una duda que querría despejar, respecto del .now, sería mejor usarlo en el servicio cuando estemos seteando los atributos en lugar de usarlo en la entidad?

2022-08-23 02:25 UTC, turcoamado approved these changes
Con respecto a tu consulta sobre donde instanciar la fecha, si en la enetidad o el servicio. Yo creo, creeeeeeo que al utilizar las annotations que les pase las fechas se instancian solas tanto para el create como para el update, deberia chequear (hace bastante no las uso, pero el grupo anterior las utilizo de esta manera y no tuvo inconvenientes).
Ahora, si hay que hacerlo a mano no veo mal que este instanciado en la entidad, porque ya sabemos de antemano que la fecha de creacion va a ser esa, pero tampoco esta mal que se ponga en el servicio ya que toda la logica va alli, por lo que a mi me daria lo mismo, la dejaria en la entidad para que este definido ya aca

2022-08-23 12:45 UTC, merged