OT278-45
alkemyTech/OT278-server pull request #52
Opened 2022-09-06 05:58 UTC by FedericoCarrasco

Summary:

- Add DELETE endpoint to categories.

Duda: Usé el método extra para validar la existencia de la entidad con ese id. 

Por un lado me parece más limpio porque se puede reutilizar ese bloque de código, pero por el otro me parece que al tener el método nombrado "getFromRepositoryById" no le da la idea al que lo lee de que se está chequeando si la entidad existe. 
(Además de que no estoy usando la entidad devuelta)

Debería implementar la validación por fuera de ese método para el delete?

Postman example:

<img width="850" alt="Screen Shot 2022-09-06 at 02 43 52" src="https://user-images.githubusercontent.com/75759984/188557295-b8467842-7b1e-46fe-83ec-3db48f38a24a.png">

Database example:

<img width="600" alt="Screen Shot 2022-09-06 at 02 44 24" src="https://user-images.githubusercontent.com/75759984/188557337-f6d7052c-8263-43e4-b387-127c474ab652.png">

2022-09-06 19:43 UTC, turcoamado requested changes
Con respecto a tus consultas, podes utilizar otro metodo para la validacion, es totalmente correcto y si es cierto que se puede reutilizar, si no te gusta el nombre le podes poner otro que describa un poco mejor lo que estas haciendo, con un getCategoryById creo que estaria bien, pero podes ser creativo (pero quizas no hace falta aclarar que es del repositorio)
Entonces, es lo mismo implementar la validacion dentro del metodo que efectivamente hace el delete o en uno por fuera, seguramente sea util el que realizaste para traer por id.
Y si, imagino que podrias usar la entidad traida para setearle la fecha de update, pero dentro del metodo que elimina no del que buscas la entidad.

Respecto al PR, te esta faltando que sea ejecutable unicamente por el usuario administrador

2022-09-06 20:16 UTC, FedericoCarrasco commented
El controller de categories entero ya pedía rol administrador, por eso no aparece en mis cambios. Lo cambio y pongo endpoint por endpoint o así está bien?

2022-09-06 20:36 UTC, FedericoCarrasco commented
Cambié también el nombre del método en el ticket que tuve antes de TestimonialService y agregué ahí también lo del UpdateTimestamp que me había olvidado 😬

2022-09-07 20:37 UTC, turcoamado approved these changes
Bien! Ahi entendi lo que me decias de category y los permisos. Si bien tenes razon no es prolijo, porque se podria agregar un endpoint que no requiera ser admin y ahi habria que buscar endpoint por endpoint para ver a cual hay que ponerle el permiso. Pero no lo cambies, porque revise todos y ninguno lo va a requerir, solo tenganlo en cuenta nada mas.

2022-09-07 20:55 UTC, merged