feature-33
alkemyTech/OT278-server pull request #53
Opened 2022-09-06 16:44 UTC by GianBarritta

**SUMMARY**

- Delete user endpoint.

2022-09-06 19:46 UTC, turcoamado requested changes

2022-09-06 19:46 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/auth/UserService.java
> +        repository.delete(user);
Te falta chequear que el usuario que se esta eliminando es el que esta logueado, con este endpoint asi como lo codificaste estas eliminando cualquier usuario que matchee con el id pasado por parametro

2022-09-06 21:32 UTC, GianBarritta commented on src/main/java/com/alkemy/ong/security/auth/UserService.java
> +        repository.delete(user);
no se bien como seria ahi, se me ocurrio esto que voy a pushear ahora..

2022-09-08 20:00 UTC, turcoamado requested changes

2022-09-08 20:00 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/auth/UserService.java
> +    private boolean compareUsers(User user) {
esta bien encarado pero le estas pifiando al dato, si te das cuenta comparas dos veces con lo mismo, porque el user es efectivamente el mismo que userDetails. Lo que tenes que hacer es obtener los datos desde el token, el token es lo que te dice que usuario esta conectado, con eso obtenes el userName o mail y realizas la comparacion contra el user que te vino por request

2022-09-09 22:47 UTC, GianBarritta commented on src/main/java/com/alkemy/ong/security/auth/UserService.java
> +    private boolean compareUsers(User user) {
![Screenshot from 2022-09-09 15-07-27](https://user-images.githubusercontent.com/98044720/189455608-f139ae0e-9177-4b15-8e49-69e1ef664274.png)

2022-09-09 22:48 UTC, GianBarritta commented
![Screenshot from 2022-09-09 15-07-27](https://user-images.githubusercontent.com/98044720/189455659-1d86b343-93c7-4d8a-aec7-9172cbf9e2d4.png)

2022-09-11 00:56 UTC, turcoamado approved these changes
Te lo dejo como aprobado, pero fijate de corregirle al menos el tema de los dos puntos en el parametro del endpoint, no deberian estar

2022-09-11 00:56 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/controller/UserController.java
> +    @DeleteMapping("/:{id}")
Los dos puntos adelante del {id} no deberian ir. De hecho no se como es que te esta funcioando de esta manera, vos le deberias pasar el id sin los :

2022-09-11 00:56 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/auth/UserService.java
> +            throw new NotFoundException(messageSource.getMessage("not-found", new Object[]{"User"},Locale.US));
Los "User" que estan en el mensaje deberian ir al properties tambien.

2022-09-12 14:07 UTC, GianBarritta commented on src/main/java/com/alkemy/ong/security/controller/UserController.java
> +    @DeleteMapping("/:{id}")
Me confundi con lo que pedia el ticket, pense que la sintaxis sería asi, ya lo corrijo. No se me lo tomo igual asi.. pero ya lo modifico!

2022-09-12 14:07 UTC, GianBarritta commented on src/main/java/com/alkemy/ong/security/auth/UserService.java
> +            throw new NotFoundException(messageSource.getMessage("not-found", new Object[]{"User"},Locale.US));
okey

2022-09-12 14:23 UTC, merged