Add Slides to public endpoint
alkemyTech/OT278-server pull request #57
Opened 2022-09-07 12:43 UTC by OscarTalero

Add Slides to public endpoint.

- In the public data endpoint of the Organization, the list of Slides ordered by the "order" field must be added. (The "order" field was changed by the "position" field of the Slide entity)

- The Slides will be those belonging to the Organization, based on the "organization_id" field that should correspond to the Organization that is being returned

2022-09-08 02:14 UTC, turcoamado requested changes
En lugar de realizar un nuevo endpoint lo que habia que hacer es modificar el que ya estaba hecho con _/public_. Quizas te confundiste con lo que decia de organization_id, que si, puede estar confuso.
Pero la idea es que el mismo de datos publicos ahora brinde las slides, para eso obvio hay que utilizar el id de la organization (aunque en realidad vamos a tener una unica organization porque lo asumimos de esa forma), pero eso lo obtenemos como ya esta hecho en el service en la linea 45:` Organization org = organizationRepository.findAll().get(0)` y ahi ya podrias tener el id.
De todos modos te estaba faltando filtrar las slides relacionadas a ese id

2022-09-08 02:14 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
> +                    "There is no Organization with the entered Id");
Recorda que todo lo que es mensajes hacia el usuario deben ir en el properties dedicado para tal fin

2022-09-08 02:14 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
> +            slideEntityList = slideRepository.findAllByOrderByPositionAsc();
Estas obteniendo todos los slides y no estas filtrando por organization_id

2022-09-09 13:33 UTC, OscarTalero commented on src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
> +            slideEntityList = slideRepository.findAllByOrderByPositionAsc();
Se elimina este método y se implementa uno nuevo para filtrar por organization_id y organizar por el campo position los Slides

2022-09-10 01:40 UTC, turcoamado approved these changes
Eliminate lo que dejaste comentado y estamos. Lo dejo como aprobado

2022-09-10 01:40 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +   /* public ResponseEntity<?> getOrganizationDetails() {
Esto que te quedo comentado eliminalo porfa

2022-09-10 01:40 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +       // return mapper.orgEntity2orgPublicDTO(orgPublicInfo);
Esto que te quedo comentado borralo porfa

2022-09-10 01:40 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/SlideServiceImpl.java
> +        Collections.sort(slides, Comparator.comparing(SlideResponseDTO::getPosition));
Muy bueno esto

2022-09-10 12:36 UTC, merged