Create News model and repository
alkemyTech/OT278-server pull request #6
Opened 2022-08-20 14:48 UTC by OscarTalero

Create News model and repository

2022-08-21 16:59 UTC, turcoamado requested changes
Oacar te deje algunos comentarios. Disculpame la falta de tildes, tengo la pc con la configuracion en ingles

2022-08-21 16:59 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/News.java
> +    @Column(name = "name", length = 50, nullable = false)
En todos los campos que son nullable = false te faltaria agregar un mensaje de error, esto seria para que si en el request no se envia el campo entonces me salte el mensaje. Se podria hacer mediante la annotation @NotNull y podria quedar por ejemplo como: `@NotNull(message = "Name cannot be null")`

2022-08-21 16:59 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/News.java
> +@SQLDelete(sql = "UPDATE news_deleted SET news_deleted = true WHERE news_id=?")
Aca esta bien definida la query pero mal la variable, fijate que usas news_deleted y en el _@where_ estas usando deleted, y lo mismo en la variable dentro de la clase. Tienen que ser en los tres lugares la misma

2022-08-21 16:59 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/News.java
> +    @CreationTimestamp
Yo tambien agregaria un caso mas para la fecha de actualizacion, con la annotation `@UpdateTimestamp`

2022-08-21 17:31 UTC, OscarTalero commented on src/main/java/com/alkemy/ong/model/News.java
> +    @Column(name = "name", length = 50, nullable = false)
Si lo pensé, pero lo decidí así para que fuera resuelto en el formulario en el Front.

2022-08-21 17:32 UTC, OscarTalero commented on src/main/java/com/alkemy/ong/model/News.java
> +@SQLDelete(sql = "UPDATE news_deleted SET news_deleted = true WHERE news_id=?")
Si, tienes razón, tal vez me dejé por el auto completado.

2022-08-21 17:34 UTC, OscarTalero commented on src/main/java/com/alkemy/ong/model/News.java
> +    @CreationTimestamp
Tenía esa duda, porque las noticias tienen fecha de creación pero no sabía si se podían actualizar, ya lo implemento.

2022-08-21 21:53 UTC, OscarTalero commented on src/main/java/com/alkemy/ong/model/News.java
> +    @Column(name = "name", length = 50, nullable = false)
ok

2022-08-23 01:16 UTC, turcoamado approved these changes
buenisimo!

2022-08-23 11:43 UTC, merged