ending delete testimonial endpoint
alkemyTech/OT278-server pull request #65
Opened 2022-09-08 19:34 UTC by matiasnb28

Además de mi ticket, también estuvimos viendo y organizando un poco mejor el tema de los roles y la seguridad para poder usar los mismo de forma correcta.

2022-09-09 22:41 UTC, turcoamado requested changes
Muy bueno el laburo sobre los roles! Te deje dos observaciones con respecto al PR en si

2022-09-09 22:41 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +    @DeleteMapping("/:{id}")
el : que pusiste no hace falta, es mas, te esta funcionando asi?

2022-09-09 22:41 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/TestimonialServiceImpl.java
> +            entity.setUpdateDate(LocalDateTime.now());
te esta guardando efectivamente la fecha de actualizacion? porque se lo seteas a la entidad que obtenes pero nunca se guarda en la DB. Si se esta guardando es seguramente porque la annotation que se usa en la entity hace ese laburo, pero lo chequeas porfa?

2022-09-09 22:41 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/TestimonialServiceImpl.java
> +        }catch (Exception e) {
Deberia haber otro catch indicando que sucede si el objeto entity que recuperas es null, eso sucederia porque metiste un id fruta en el request

2022-09-10 17:06 UTC, matiasnb28 commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +    @DeleteMapping("/:{id}")
Me funcionaba pero porque estaba usando mal el postman y lo estaba "harcodeando", ya lo modifico

2022-09-10 17:06 UTC, matiasnb28 commented on src/main/java/com/alkemy/ong/service/impl/TestimonialServiceImpl.java
> +            entity.setUpdateDate(LocalDateTime.now());
Estuve chusmeando esto y tenías razón, no la estaba guardando. Ahí le hice le cambio. No sé si es la forma más efectiva. Si la hay, me gustaría que me dieras tu opinión

2022-09-10 17:06 UTC, matiasnb28 commented on src/main/java/com/alkemy/ong/service/impl/TestimonialServiceImpl.java
> +        }catch (Exception e) {
Eso está en el método:   Testimonial entity = getTestimonialById(id); que está arriba del método eliminar. Si trae uno que no existe, tira un exception.

2022-09-10 17:46 UTC, turcoamado approved these changes
Me gusta que hayas agregado el rol developer, aunque dudo que lo utilicemos para algo

2022-09-10 17:46 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/TestimonialServiceImpl.java
> +        }catch (Exception e) {
Quizas hay una manera de que lo haga la annotation (u otra anotacion) pero realmente no lo recuerdo. Lo que hiciste aca si esta bien

2022-09-10 22:08 UTC, merged