Enpoind delete comments by user owner or admin
alkemyTech/OT278-server pull request #77
Opened 2022-09-13 00:52 UTC by OscarTalero

Create Endpoint to delete comments by owner user or admin.

2022-09-14 02:18 UTC, turcoamado requested changes
Lo que planteate esta muy bien, prestale atencion a los detalles que te mencione, como inyectar la interface en el controlador y no la implementacion, y el rol que estas usando ROLE_ADMIN y ustedes creo habian definido como ADMIN.

Te consulto, donde miraste documentacion o algo para hacer esto? Porque son exactamente los mismos tres metodos que ya codifico un grupo en su momento y ahora me llamo la atencion, lo veia conocido entonces fui a buscar y encontre lo mismo, nombres de metodos, variables e incluso el ROLE_ADMIN

2022-09-14 02:18 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CommentController.java
> +        commentServiceImlp.existId(id);
Se podria tal vez haber implementado de forma diferente para que no quede como colgada la llamada ahi y entonces que devuelva un boolean o algo por el estilo, pero no esta mal, cumple.

Ahora, lo que si esta mal es que se esta utilizando directamente la implementacion del servicio, esto seguro se me paso en un PR previo, pero porfa cambialo, en el controller se debe inyectar la interface no la implementacion.

2022-09-14 02:18 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
> +   // @Override
este se descomentaria cuando se acomode lo del controller, que se llame a la interface y no a la implementacion

2022-09-14 02:18 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
> +            return (username.equals(emailUserCreator) || authorityUser.equals("ROLE_ADMIN"));
No estaban usando solo "ADMIN" para el usuario administrador?

2022-09-16 00:37 UTC, turcoamado approved these changes

2022-09-16 12:18 UTC, OscarTalero commented
Merge to develop

2022-09-16 12:18 UTC, closed without merging