Sendgrid OT278-28
alkemyTech/OT278-server pull request #8
Opened 2022-08-21 23:19 UTC by LucasLopezd

SUMARY:

- SendGrid configuration added
- EmailService added

2022-08-23 01:52 UTC, turcoamado requested changes
Te deje un comentario respecto a tu pregunta y otro mas. Lo que te esta faltando aca es crear la interface del service, con la firma del metodo sendEmail(...) y entonces en la implementacion deberia hacerse un override de ese metodo (y cambiar el nombre de la clase para indicar que es una implementacion

2022-08-23 01:52 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/EmailService.java
> +        // TODO: <- return Response or String?
Segun como se piense podria ser uno o el otro, asi que podes tomar la decision que creas conveniente. No se cual seria mejor realmente, si retornas un response desde donde se invoque se debera tratar la respuesta y agregar los mensajes correspondientes, pero si retornas un string deberias creo retornar el body, para tener toda la informacion, y quizas si lo miramos asi conviene retornar el response.
Un detalle, para comparar contra los codigos de error conviene hacer HttpStatus.OK para el 200 y HttpStatus.ACEPTED para el 202, la razon? porque siempre intentaremos evitar todo lo que sea hardcoded (una cuestion de buenas practicas)

2022-08-23 01:52 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/EmailService.java
> +            request.setMethod(method);
el method podria ser sacado de los parametros y directamente poner Method.POST. Lo mismo con el endpoint, ya que siempre sera "mail/send", que podria estar como variable estatica de clase o bien en algun enum de constantes (segun se utilicen mas para esto, pero quizas cuando haya que implementar los envio de mails al registro y demas surgen mas)

2022-08-23 12:09 UTC, LucasLopezd commented on src/main/java/com/alkemy/ong/service/EmailService.java
> +            request.setMethod(method);
Perfecto, haré los cambios. 
Lo plantié de esa manera porque en el ticket dice que "en ciertos endpoints" se hará envíos de mails, entonces entendí que este servicio iba a ser invocado en varios endpoints distintos, por eso permití que sea mas perzonalizable, pero lo voy a modificar e implementar la interface correspondiente.

2022-08-24 12:32 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/EmailService.java
> +            request.setMethod(method);
Claro si, se va a utilizar en ciertos endpoints, no recuerdo ahora si eran dos o tres, pero siempre sera un POST y mail/send. De todos modos estaba bien lo que habias planteado, era una modificacion que no hace a la funcionalidad

2022-08-24 12:32 UTC, turcoamado approved these changes
Buenisimo!

2022-08-24 14:20 UTC, merged