Add pagination to Testimonials
alkemyTech/OT278-server pull request #84
Opened 2022-09-15 13:00 UTC by OscarTalero

Add pagination to Testimonial

2022-09-16 00:38 UTC, turcoamado requested changes
Aca te esta faltando agregar los links a la pagina siguiente y anterior si hubiesen

2022-09-17 17:52 UTC, OscarTalero commented
Added links to pagination testimonial endpoint

2022-09-18 16:23 UTC, turcoamado requested changes
Oscar tenes muchisimos cambios aca, te trajiste lo ultimo que esta en develop? Tengo miedo que se modifiquen otras cosas.

Con respecto al PR, habias hecho uno sobre esto y solamente te faltaban los links a la pagina siguiente y anterior, pero vi que cerraste el PR y armaste este. Aca lo estas implementando? Porque no note que hayas utilizado el metodo _mapPage()_ que se creo con ese fin (ver la clase **GenericMapper**)

Pero primero actualizate el branch con lo que hay en develop

2022-09-20 12:16 UTC, OscarTalero commented
Vale Turco lo voy a refactorizar con el metodo que indicas, lo habia implementado con HateoAs

2022-09-20 12:19 UTC, OscarTalero commented
Actualizo develop, cierro esta PR y abro una nueva para evitar conflictos

2022-09-20 12:59 UTC, closed without merging